FROM oven/bun:alpine AS base

WORKDIR /app

FROM base AS build

# Cache packages installation
COPY package.json package.json
COPY ./packages/lockinspiel-backend-common/package.json ./packages/lockinspiel-backend-common/package.json
COPY bun.lock bun.lock
COPY ./packages/lockinspiel-frontend/package.json ./packages/lockinspiel-frontend/package.json

RUN bun install && \
  apk add nodejs

COPY ./packages/lockinspiel-frontend ./packages/lockinspiel-frontend
COPY ./packages/lockinspiel-backend-common/src ./packages/lockinspiel-backend-common/src
COPY ./packages/lockinspiel-backend-common/tsconfig.json ./packages/lockinspiel-backend-common/tsconfig.json

ENV NODE_ENV=production
WORKDIR /app/packages/lockinspiel-frontend

RUN bunx ng build

FROM base AS runner

COPY --from=build /app/packages/lockinspiel-frontend/dist dist

ENV NODE_ENV=production

CMD ["bun", "./dist/lockinspiel-frontend/server/server.mjs"]
