services:
  db:
    volumes:
      # PGDATA directory is persisted between restarts
      - pgdata:/var/lib/postgresql
      - ./postgres/init-user-db.sh:/docker-entrypoint-initdb.d/10_userdb.sh
    image: timescale/timescaledb:latest-pg18
    restart: unless-stopped
    ports:
      - 5432:5432
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

  kong:
    image: kong:3
    restart: unless-stopped
    ports:
      - 8000:8000/tcp
      - 8443:8443/tcp
    volumes:
      - ./volumes/api:/kong/declarative/
      - type: tmpfs
        target: /tmp
      - type: tmpfs
        target: /var/run/kong
      # - ./api/kong.yml:/kong/declarative/kong.yml
    environment:
      KONG_PREFIX: /var/run/kong
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/declarative/kong.yml
      KONG_DNS_ORDER: LAST,A,CNAME
      KONG_PLUGINS: request-transformer,cors,key-auth,acl,basic-auth,request-termination,ip-restriction,opentelemetry,prometheus
      KONG_NGINX_PROXY_PROXY_BUFFER_SIZE: 160k
      KONG_NGINX_PROXY_PROXY_BUFFERS: 64 160k
      KONG_TRACING_INSTRUMENTATIONS: all
      KONG_TRACING_SAMPLING_RATE: 1.0
      KONG_STATUS_LISTEN: 0.0.0.0:8100
    # https://unix.stackexchange.com/a/294837
    # entrypoint: bash -c 'eval "echo \"$$(cat /kong/declarative/temp.yml)\"" > /kong/declarative/kong.yml && /docker-entrypoint.sh kong docker-start'

  lgtm:
    image: grafana/otel-lgtm
    ports:
      - 3000:3000

  garage:
    image: dxflrs/garage:v2.3.0
    restart: unless-stopped
    ports:
      - 3900:3900
    volumes:
      - ./volumes/garage/garage.toml:/etc/garage.toml
      - garagemeta:/var/lib/garage/meta
      - garagedata:/var/lib/garage/data
    environment:
      GARAGE_CONFIG_FILE: /etc/garage.toml
      GARAGE_DEFAULT_ACCESS_KEY: garageadminadmin
      GARAGE_DEFAULT_SECRET_KEY: garageadminadmin
      GARAGE_DEFAULT_BUCKET: default-bucket
    command: ["/garage", "server", "--single-node", "--default-bucket"]

  jwkinator:
    build:
      args:
        STEPUID: 10000
        STEPGID: 10000
        STEP: /etc/config/kratos-keys
        STEPPATH: /etc/config/kratos-keys
      context: ./docker/jwkinator
    volumes:
      - type: volume
        source: kratoskeys
        target: /etc/config/kratos-keys
        read_only: false
    restart: on-failure

  # From https://github.com/ory/kratos/blob/master/quickstart.yml
  kratos-migrate:
    image: oryd/kratos:v26.2.0
    depends_on:
      db:
        condition: service_healthy
      jwkinator:
        condition: service_completed_successfully
    environment:
      - DSN=postgres://auth_service:example@db:5432/docker?search_path=auth,public&sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      - type: bind
        source: ./volumes/kratos
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure

  kratos-selfservice-ui-node:
    image: oryd/kratos-selfservice-ui-node:v26.2.0
    depends_on:
      - kratos
    ports:
      - '4455:4455'
    environment:
      - KRATOS_PUBLIC_URL=http://kratos:4433/
      - KRATOS_BROWSER_URL=http://localhost:4433/
      # - KRATOS_PUBLIC_URL=https://staging.lockinspiel.live
      # - KRATOS_BROWSER_URL=https://staging.lockinspiel.live
      - COOKIE_SECRET=changeme
      - CSRF_COOKIE_NAME=ory_csrf_ui
      - CSRF_COOKIE_SECRET=changeme
      - PORT=4455
      - SECURITY_MODE=
    restart: on-failure

  kratos:
    depends_on:
      kratos-migrate:
        condition: service_completed_successfully
      db:
        condition: service_healthy
    image: oryd/kratos:v26.2.0
    ports:
      - '4433:4433' # public
      - '4434:4434' # admin
    restart: unless-stopped
    environment:
      - DSN=postgres://auth_service:example@db:5432/docker?search_path=auth,public&sslmode=disable&max_conns=20&max_idle_conns=4
      - LOG_LEVEL=trace
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    user: "10000:10000"
    volumes:
      - type: bind
        source: ./volumes/kratos
        target: /etc/config/kratos
      - type: volume
        source: kratoskeys
        target: /etc/config/kratos-keys

  web-timekeeper:
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 10
    volumes:
      - ./docker/jwkinator/certificate.pem:/etc/config/keys/certificate.pem
    build:
      args:
        SERVICE: lockinspiel-timekeeper
      context: ./rust
    environment:
      DATABASE_URL: postgres://timekeeper_service:example@db/docker
      AUTH_SERVICE: http://kratos
      AUTH_CERTIFICATE_PATH: /etc/config/keys/certificate.pem
      SERVICE_TYPE: timekeeper
      OTEL_EXPORTER_OTLP_ENDPOINT: http://lgtm:4317
      LISTEN_ADDR: "[::]:3000"
    deploy:
      mode: replicated
      replicas: 1

  web-timekeeper-health:
    image: curlimages/curl
    network_mode: "service:web-timekeeper"  # Critical: shares api's network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 45s
    entrypoint: ["sleep", "infinity"]  

  web-user:
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - ./docker/jwkinator/certificate.pem:/etc/config/keys/certificate.pem
    build:
      args:
        SERVICE: lockinspiel-user
      context: ./rust
    environment:
      AUTH_SERVICE: http://kratos
      AUTH_CERTIFICATE_PATH: /etc/config/keys/certificate.pem
      DATABASE_URL: postgres://user_service:example@db/docker
      SERVICE_TYPE: user
      OTEL_EXPORTER_OTLP_ENDPOINT: http://lgtm:4317
      LISTEN_ADDR: "[::]:3000"
      S3_BUCKET_NAME: default-bucket
      S3_BUCKET_REGION: garage
      S3_BUCKET_ACCESS_KEY: garageadminadmin
      S3_BUCKET_SECRET_KEY: garageadminadmin
      S3_BUCKET_PATH_STYLE: true
      S3_BUCKET_ENDPOINT: http://localhost:3900
      S3_BUCKET_INTERNAL_ENDPOINT: http://garage:3900
      # RUST_LOG: debug
    deploy:
      mode: replicated
      replicas: 1

  web-timesync:
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 5s
      timeout: 5s
      retries: 10
    build:
      args:
        SERVICE: lockinspiel-timesync
      context: ./rust
    environment:
      LISTEN_ADDR: "[::]:3000"
    deploy:
      mode: replicated
      replicas: 1

volumes:
  pgdata:
  kratoskeys:
  garagemeta:
  garagedata:
