metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"
db_engine = "lmdb"

block_size = "1048576"

replication_factor = 1

rpc_bind_addr = "[::]:3901"
rpc_public_addr = "127.0.0.1:3901"
rpc_secret = "166b0e60eac5f4942f6cb3b56c632c32629cfdd88195490e359686a9cec8c1b8"

[s3_api]
s3_region = "garage"
api_bind_addr = "[::]:3900"
root_domain = ".s3.garage.localhost"

[s3_web]
bind_addr = "[::]:3902"
root_domain = ".web.garage.localhost"
index = "index.html"

[admin]
api_bind_addr = "[::]:3903"
admin_token = "ghTYOvDGFz96LQNfS4Ex7PLXqicjUjDjoS8pk6W02lM="
metrics_token = "wecyB49udvHtTqb3zsAV/IeNur43O7UGd23RTIdaCuQ="
