server.port=${LISTEN_PORT:3000}
management.opentelemetry.tracing.export.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT}
management.opentelemetry.metrics.export.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT}
management.opentelemetry.logging.export.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT}
scalar.enabled=true
scalar.path=/analyzer/openapi
springdoc.api-docs.path = /analyzer/openapi/json
spring.application.name=analyzer
spring.flyway.baselineOnMigrate=true
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/lockinspiel?user=${DB_USER:${USER:docker}}&password=${DB_PASSWORD}}
