// This file is auto-generated by @hey-api/openapi-ts

export const auth_DatabaseUserPasswordSchema = {
    type: 'object',
    required: [
        'password'
    ],
    properties: {
        password: {
            type: 'string'
        }
    }
} as const;

export const auth_InsertableDatabaseUserSchema = {
    allOf: [
        {
            $ref: '#/components/schemas/auth_DatabaseUserPassword'
        },
        {
            type: 'object',
            required: [
                'username'
            ],
            properties: {
                username: {
                    type: 'string'
                }
            }
        }
    ]
} as const;

export const auth_LoginSchema = {
    oneOf: [
        {
            type: 'object',
            required: [
                'credentials'
            ],
            properties: {
                credentials: {
                    type: 'object',
                    required: [
                        'username',
                        'password'
                    ],
                    properties: {
                        password: {
                            type: 'string'
                        },
                        username: {
                            type: 'string'
                        }
                    }
                }
            }
        },
        {
            type: 'object',
            required: [
                'refresh_token'
            ],
            properties: {
                refresh_token: {
                    type: 'object',
                    properties: {
                        token: {
                            type: [
                                'string',
                                'null'
                            ],
                            description: 'If the refresh token is null, it\'s assumed that the token\nwill be provided via a cookie'
                        }
                    }
                }
            }
        }
    ]
} as const;

export const auth_LoginTokenSchema = {
    type: 'object',
    required: [
        'access_token'
    ],
    properties: {
        access_token: {
            type: 'string'
        }
    }
} as const;

export const user_InsertableUserProfileSchema = {
    type: 'object',
    required: [
        'display_name',
        'bio'
    ],
    properties: {
        bio: {
            type: 'string'
        },
        display_name: {
            type: 'string'
        }
    }
} as const;

export const user_PutAvatarQuerySchema = {
    type: 'object',
    required: [
        'file_extension'
    ],
    properties: {
        file_extension: {
            type: 'string'
        }
    }
} as const;

export const user_UserProfileSchema = {
    type: 'object',
    required: [
        'display_name',
        'bio'
    ],
    properties: {
        avatar_location: {
            type: [
                'string',
                'null'
            ]
        },
        bio: {
            type: 'string'
        },
        display_name: {
            type: 'string'
        }
    }
} as const;

export const user_UserProfileChangesetSchema = {
    type: 'object',
    required: [
        'display_name',
        'bio'
    ],
    properties: {
        bio: {
            type: 'string'
        },
        display_name: {
            type: 'string'
        }
    }
} as const;

export const timekeeper_TimerSchema = {
    type: 'object',
    required: [
        'time_split',
        'work',
        'time_split_timer',
        'start_time',
        'end_time',
        'tags'
    ],
    properties: {
        time_split: {
            anyOf: [
                {
                    format: 'integer',
                    default: 0,
                    type: 'string'
                },
                {
                    type: 'integer'
                }
            ]
        },
        work: {
            type: 'boolean'
        },
        time_split_timer: {
            anyOf: [
                {
                    format: 'integer',
                    default: 0,
                    type: 'string'
                },
                {
                    type: 'integer'
                }
            ]
        },
        start_time: {
            anyOf: [
                {
                    type: 'Date'
                },
                {
                    format: 'date-time',
                    type: 'string'
                },
                {
                    format: 'date',
                    type: 'string'
                },
                {
                    type: 'number'
                }
            ]
        },
        end_time: {
            anyOf: [
                {
                    type: 'Date'
                },
                {
                    format: 'date-time',
                    type: 'string'
                },
                {
                    format: 'date',
                    type: 'string'
                },
                {
                    type: 'number'
                }
            ]
        },
        tags: {
            type: 'array',
            items: {
                anyOf: [
                    {
                        format: 'integer',
                        default: 0,
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            }
        }
    },
    $id: '#/components/schemas/Timer'
} as const;

export const timekeeper_InsertableTimerSchema = {
    type: 'object',
    required: [
        'time_split_timer',
        'start_time',
        'end_time',
        'tags'
    ],
    properties: {
        time_split_timer: {
            anyOf: [
                {
                    format: 'integer',
                    default: 0,
                    type: 'string'
                },
                {
                    type: 'integer'
                }
            ]
        },
        start_time: {
            anyOf: [
                {
                    type: 'Date'
                },
                {
                    format: 'date-time',
                    type: 'string'
                },
                {
                    format: 'date',
                    type: 'string'
                },
                {
                    type: 'number'
                }
            ]
        },
        end_time: {
            anyOf: [
                {
                    type: 'Date'
                },
                {
                    format: 'date-time',
                    type: 'string'
                },
                {
                    format: 'date',
                    type: 'string'
                },
                {
                    type: 'number'
                }
            ]
        },
        tags: {
            type: 'array',
            items: {
                anyOf: [
                    {
                        format: 'integer',
                        default: 0,
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            }
        }
    },
    $id: '#/components/schemas/InsertableTimer'
} as const;

export const timekeeper_TagSchema = {
    type: 'object',
    required: [
        'name'
    ],
    properties: {
        name: {
            type: 'string'
        }
    },
    $id: '#/components/schemas/Tag'
} as const;

export const timekeeper_TagWIDSchema = {
    type: 'object',
    required: [
        'id',
        'name'
    ],
    properties: {
        id: {
            anyOf: [
                {
                    format: 'integer',
                    default: 0,
                    type: 'string'
                },
                {
                    type: 'integer'
                }
            ]
        },
        name: {
            type: 'string'
        }
    },
    $id: '#/components/schemas/TagWID'
} as const;

export const timekeeper_TimeSplitTimerSchema = {
    type: 'object',
    required: [
        'len',
        'name',
        'work'
    ],
    properties: {
        len: {
            anyOf: [
                {
                    format: 'integer',
                    default: 0,
                    type: 'string'
                },
                {
                    type: 'integer'
                }
            ]
        },
        name: {
            type: 'string'
        },
        work: {
            type: 'boolean'
        }
    },
    $id: '#/components/schemas/TimeSplitTimer'
} as const;

export const timekeeper_TimeSplitTimerWOrderSchema = {
    type: 'object',
    required: [
        'order_idx',
        'len',
        'name',
        'work'
    ],
    properties: {
        order_idx: {
            anyOf: [
                {
                    format: 'integer',
                    default: 0,
                    type: 'string'
                },
                {
                    type: 'integer'
                }
            ]
        },
        len: {
            anyOf: [
                {
                    format: 'integer',
                    default: 0,
                    type: 'string'
                },
                {
                    type: 'integer'
                }
            ]
        },
        name: {
            type: 'string'
        },
        work: {
            type: 'boolean'
        }
    },
    $id: '#/components/schemas/TimeSplitTimerWOrder'
} as const;

export const timekeeper_TimeSplitTimerWIDSchema = {
    type: 'object',
    required: [
        'id',
        'order_idx',
        'len',
        'name',
        'work'
    ],
    properties: {
        id: {
            anyOf: [
                {
                    format: 'integer',
                    default: 0,
                    type: 'string'
                },
                {
                    type: 'integer'
                }
            ]
        },
        order_idx: {
            anyOf: [
                {
                    format: 'integer',
                    default: 0,
                    type: 'string'
                },
                {
                    type: 'integer'
                }
            ]
        },
        len: {
            anyOf: [
                {
                    format: 'integer',
                    default: 0,
                    type: 'string'
                },
                {
                    type: 'integer'
                }
            ]
        },
        name: {
            type: 'string'
        },
        work: {
            type: 'boolean'
        }
    },
    $id: '#/components/schemas/TimeSplitTimerWID'
} as const;

export const timekeeper_TimeSplitNoTimersSchema = {
    type: 'object',
    required: [
        'name',
        'description'
    ],
    properties: {
        name: {
            type: 'string'
        },
        description: {
            nullable: true,
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    $id: '#/components/schemas/TimeSplitNoTimers'
} as const;

export const timekeeper_TimeSplitSchema = {
    type: 'object',
    required: [
        'timers',
        'name',
        'description'
    ],
    properties: {
        timers: {
            type: 'array',
            items: {
                type: 'object',
                required: [
                    'len',
                    'name',
                    'work'
                ],
                properties: {
                    len: {
                        anyOf: [
                            {
                                format: 'integer',
                                default: 0,
                                type: 'string'
                            },
                            {
                                type: 'integer'
                            }
                        ]
                    },
                    name: {
                        type: 'string'
                    },
                    work: {
                        type: 'boolean'
                    }
                },
                $id: '#/components/schemas/TimeSplitTimer'
            }
        },
        name: {
            type: 'string'
        },
        description: {
            nullable: true,
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    $id: '#/components/schemas/TimeSplit'
} as const;

export const timekeeper_TimeSplitWIDSchema = {
    type: 'object',
    required: [
        'id',
        'timers',
        'name',
        'description'
    ],
    properties: {
        id: {
            anyOf: [
                {
                    format: 'integer',
                    default: 0,
                    type: 'string'
                },
                {
                    type: 'integer'
                }
            ]
        },
        timers: {
            type: 'array',
            items: {
                type: 'object',
                required: [
                    'id',
                    'order_idx',
                    'len',
                    'name',
                    'work'
                ],
                properties: {
                    id: {
                        anyOf: [
                            {
                                format: 'integer',
                                default: 0,
                                type: 'string'
                            },
                            {
                                type: 'integer'
                            }
                        ]
                    },
                    order_idx: {
                        anyOf: [
                            {
                                format: 'integer',
                                default: 0,
                                type: 'string'
                            },
                            {
                                type: 'integer'
                            }
                        ]
                    },
                    len: {
                        anyOf: [
                            {
                                format: 'integer',
                                default: 0,
                                type: 'string'
                            },
                            {
                                type: 'integer'
                            }
                        ]
                    },
                    name: {
                        type: 'string'
                    },
                    work: {
                        type: 'boolean'
                    }
                },
                $id: '#/components/schemas/TimeSplitTimerWID'
            }
        },
        name: {
            type: 'string'
        },
        description: {
            nullable: true,
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    $id: '#/components/schemas/TimeSplitWID'
} as const;
