// This file is auto-generated by @hey-api/openapi-ts

export const timekeeper_TimerSchema = {
    type: 'object',
    required: [
        'time_split',
        'start_timestamp',
        'end_timestamp',
        'work',
        'tags'
    ],
    properties: {
        time_split: {
            anyOf: [
                {
                    format: 'integer',
                    default: 0,
                    type: 'string'
                },
                {
                    type: 'integer'
                }
            ]
        },
        start_timestamp: {
            anyOf: [
                {
                    format: 'integer',
                    default: 0,
                    type: 'string'
                },
                {
                    type: 'integer'
                }
            ]
        },
        end_timestamp: {
            anyOf: [
                {
                    format: 'integer',
                    default: 0,
                    type: 'string'
                },
                {
                    type: 'integer'
                }
            ]
        },
        work: {
            type: 'boolean'
        },
        tags: {
            type: 'array',
            items: {
                anyOf: [
                    {
                        format: 'integer',
                        default: 0,
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            }
        }
    },
    $id: '#/components/schemas/Timer'
} as const;

export const timekeeper_TimerWIDSchema = {
    type: 'object',
    required: [
        'id',
        'time_split',
        'start_timestamp',
        'end_timestamp',
        'work',
        'tags'
    ],
    properties: {
        id: {
            anyOf: [
                {
                    format: 'integer',
                    default: 0,
                    type: 'string'
                },
                {
                    type: 'integer'
                }
            ]
        },
        time_split: {
            anyOf: [
                {
                    format: 'integer',
                    default: 0,
                    type: 'string'
                },
                {
                    type: 'integer'
                }
            ]
        },
        start_timestamp: {
            anyOf: [
                {
                    format: 'integer',
                    default: 0,
                    type: 'string'
                },
                {
                    type: 'integer'
                }
            ]
        },
        end_timestamp: {
            anyOf: [
                {
                    format: 'integer',
                    default: 0,
                    type: 'string'
                },
                {
                    type: 'integer'
                }
            ]
        },
        work: {
            type: 'boolean'
        },
        tags: {
            type: 'array',
            items: {
                anyOf: [
                    {
                        format: 'integer',
                        default: 0,
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            }
        }
    },
    $id: '#/components/schemas/TimerWID'
} as const;

export const timekeeper_TagSchema = {
    type: 'object',
    required: [
        'name'
    ],
    properties: {
        name: {
            type: 'string'
        }
    },
    $id: '#/components/schemas/Tag'
} as const;

export const timekeeper_TagWIDSchema = {
    type: 'object',
    required: [
        'id',
        'name'
    ],
    properties: {
        id: {
            anyOf: [
                {
                    format: 'integer',
                    default: 0,
                    type: 'string'
                },
                {
                    type: 'integer'
                }
            ]
        },
        name: {
            type: 'string'
        }
    },
    $id: '#/components/schemas/TagWID'
} as const;

export const timekeeper_TimeSplitTimerSchema = {
    type: 'object',
    required: [
        'len',
        'name',
        'work'
    ],
    properties: {
        len: {
            anyOf: [
                {
                    format: 'integer',
                    default: 0,
                    type: 'string'
                },
                {
                    type: 'integer'
                }
            ]
        },
        name: {
            type: 'string'
        },
        work: {
            type: 'boolean'
        }
    },
    $id: '#/components/schemas/TimeSplitTimer'
} as const;

export const timekeeper_TimeSplitSchema = {
    type: 'object',
    required: [
        'name',
        'description',
        'deleted',
        'timers'
    ],
    properties: {
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        deleted: {
            type: 'boolean'
        },
        timers: {
            type: 'array',
            items: {
                type: 'object',
                required: [
                    'len',
                    'name',
                    'work'
                ],
                properties: {
                    len: {
                        anyOf: [
                            {
                                format: 'integer',
                                default: 0,
                                type: 'string'
                            },
                            {
                                type: 'integer'
                            }
                        ]
                    },
                    name: {
                        type: 'string'
                    },
                    work: {
                        type: 'boolean'
                    }
                },
                $id: '#/components/schemas/TimeSplitTimer'
            }
        }
    },
    $id: '#/components/schemas/TimeSplit'
} as const;

export const timekeeper_TimeSplitWIDSchema = {
    type: 'object',
    required: [
        'id',
        'name',
        'description',
        'deleted',
        'timers'
    ],
    properties: {
        id: {
            anyOf: [
                {
                    format: 'integer',
                    default: 0,
                    type: 'string'
                },
                {
                    type: 'integer'
                }
            ]
        },
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        deleted: {
            type: 'boolean'
        },
        timers: {
            type: 'array',
            items: {
                type: 'object',
                required: [
                    'len',
                    'name',
                    'work'
                ],
                properties: {
                    len: {
                        anyOf: [
                            {
                                format: 'integer',
                                default: 0,
                                type: 'string'
                            },
                            {
                                type: 'integer'
                            }
                        ]
                    },
                    name: {
                        type: 'string'
                    },
                    work: {
                        type: 'boolean'
                    }
                },
                $id: '#/components/schemas/TimeSplitTimer'
            }
        }
    },
    $id: '#/components/schemas/TimeSplitWID'
} as const;

export const auth_DatabaseUserPasswordSchema = {
    type: 'object',
    required: [
        'password'
    ],
    properties: {
        password: {
            type: 'string'
        }
    }
} as const;

export const auth_InsertableDatabaseUserSchema = {
    allOf: [
        {
            $ref: '#/components/schemas/auth_DatabaseUserPassword'
        },
        {
            type: 'object',
            required: [
                'username'
            ],
            properties: {
                username: {
                    type: 'string'
                }
            }
        }
    ]
} as const;

export const auth_LoginSchema = {
    type: 'object',
    required: [
        'username',
        'password'
    ],
    properties: {
        password: {
            type: 'string'
        },
        username: {
            type: 'string'
        }
    }
} as const;

export const auth_LoginTokenSchema = {
    type: 'object',
    required: [
        'access_token'
    ],
    properties: {
        access_token: {
            type: 'string'
        }
    }
} as const;
