// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type TimekeeperTimer = {
    time_split: string | number;
    start_timestamp: string | number;
    end_timestamp: string | number;
    work: boolean;
    tags: Array<string | number>;
};

export type TimekeeperTimerWid = {
    id: string | number;
    time_split: string | number;
    start_timestamp: string | number;
    end_timestamp: string | number;
    work: boolean;
    tags: Array<string | number>;
};

export type TimekeeperTag = {
    name: string;
};

export type TimekeeperTagWid = {
    id: string | number;
    name: string;
};

export type TimekeeperTimeSplitTimer = {
    len: string | number;
    name: string;
    work: boolean;
};

export type TimekeeperTimeSplit = {
    name: string;
    description: string;
    deleted: boolean;
    timers: Array<{
        len: string | number;
        name: string;
        work: boolean;
    }>;
};

export type TimekeeperTimeSplitWid = {
    id: string | number;
    name: string;
    description: string;
    deleted: boolean;
    timers: Array<{
        len: string | number;
        name: string;
        work: boolean;
    }>;
};

export type AuthDatabaseUserPassword = {
    password: string;
};

export type AuthInsertableDatabaseUser = AuthDatabaseUserPassword & {
    username: string;
};

export type AuthLogin = {
    password: string;
    username: string;
};

export type AuthLoginToken = {
    access_token: string;
};

export type TimekeeperGetIndexData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type TimekeeperGetIndexResponses = {
    /**
     * Response for status 200
     */
    200: {
        up: boolean;
    };
};

export type TimekeeperGetIndexResponse = TimekeeperGetIndexResponses[keyof TimekeeperGetIndexResponses];

export type TimekeeperGetTimersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/timekeeper/timer';
};

export type TimekeeperGetTimersErrors = {
    /**
     * Response for status 401
     */
    401: string;
    /**
     * Response for status 404
     */
    404: string;
};

export type TimekeeperGetTimersError = TimekeeperGetTimersErrors[keyof TimekeeperGetTimersErrors];

export type TimekeeperGetTimersResponses = {
    /**
     * Response for status 200
     */
    200: Array<TimekeeperTimerWid>;
};

export type TimekeeperGetTimersResponse = TimekeeperGetTimersResponses[keyof TimekeeperGetTimersResponses];

export type TimekeeperPostTimerData = {
    body: TimekeeperTimer;
    path?: never;
    query?: never;
    url: '/timekeeper/timer';
};

export type TimekeeperPostTimerErrors = {
    /**
     * Response for status 401
     */
    401: string;
};

export type TimekeeperPostTimerError = TimekeeperPostTimerErrors[keyof TimekeeperPostTimerErrors];

export type TimekeeperPostTimerResponses = {
    /**
     * Response for status 200
     */
    200: {
        timer_id: string | number;
    };
};

export type TimekeeperPostTimerResponse = TimekeeperPostTimerResponses[keyof TimekeeperPostTimerResponses];

export type TimekeeperModifyTimerData = {
    body: TimekeeperTimer;
    path: {
        id: string | number;
    };
    query?: never;
    url: '/timekeeper/timer/{id}';
};

export type TimekeeperModifyTimerErrors = {
    /**
     * Response for status 401
     */
    401: string;
    /**
     * Response for status 404
     */
    404: string;
};

export type TimekeeperModifyTimerError = TimekeeperModifyTimerErrors[keyof TimekeeperModifyTimerErrors];

export type TimekeeperModifyTimerResponses = {
    /**
     * Response for status 200
     */
    200: string;
};

export type TimekeeperModifyTimerResponse = TimekeeperModifyTimerResponses[keyof TimekeeperModifyTimerResponses];

export type TimekeeperGetTagsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/timekeeper/tag';
};

export type TimekeeperGetTagsErrors = {
    /**
     * Response for status 401
     */
    401: string;
};

export type TimekeeperGetTagsError = TimekeeperGetTagsErrors[keyof TimekeeperGetTagsErrors];

export type TimekeeperGetTagsResponses = {
    /**
     * Response for status 200
     */
    200: Array<TimekeeperTagWid>;
};

export type TimekeeperGetTagsResponse = TimekeeperGetTagsResponses[keyof TimekeeperGetTagsResponses];

export type TimekeeperAddTagData = {
    body: TimekeeperTag;
    path?: never;
    query?: never;
    url: '/timekeeper/tag';
};

export type TimekeeperAddTagErrors = {
    /**
     * Response for status 401
     */
    401: string;
};

export type TimekeeperAddTagError = TimekeeperAddTagErrors[keyof TimekeeperAddTagErrors];

export type TimekeeperAddTagResponses = {
    /**
     * Response for status 200
     */
    200: {
        tag_id: string | number;
    };
};

export type TimekeeperAddTagResponse = TimekeeperAddTagResponses[keyof TimekeeperAddTagResponses];

export type TimekeeperDeleteTagData = {
    body?: never;
    path: {
        id: string | number;
    };
    query?: never;
    url: '/timekeeper/tag/{id}';
};

export type TimekeeperDeleteTagErrors = {
    /**
     * Response for status 401
     */
    401: string;
    /**
     * Response for status 404
     */
    404: string;
};

export type TimekeeperDeleteTagError = TimekeeperDeleteTagErrors[keyof TimekeeperDeleteTagErrors];

export type TimekeeperDeleteTagResponses = {
    /**
     * Response for status 200
     */
    200: string;
};

export type TimekeeperDeleteTagResponse = TimekeeperDeleteTagResponses[keyof TimekeeperDeleteTagResponses];

export type TimekeeperModifyTagData = {
    body: TimekeeperTag;
    path: {
        id: string | number;
    };
    query?: never;
    url: '/timekeeper/tag/{id}';
};

export type TimekeeperModifyTagErrors = {
    /**
     * Response for status 401
     */
    401: string;
    /**
     * Response for status 404
     */
    404: string;
};

export type TimekeeperModifyTagError = TimekeeperModifyTagErrors[keyof TimekeeperModifyTagErrors];

export type TimekeeperModifyTagResponses = {
    /**
     * Response for status 200
     */
    200: string;
};

export type TimekeeperModifyTagResponse = TimekeeperModifyTagResponses[keyof TimekeeperModifyTagResponses];

export type TimekeeperGetTimeSplitsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/timekeeper/time-split';
};

export type TimekeeperGetTimeSplitsErrors = {
    /**
     * Response for status 401
     */
    401: string;
};

export type TimekeeperGetTimeSplitsError = TimekeeperGetTimeSplitsErrors[keyof TimekeeperGetTimeSplitsErrors];

export type TimekeeperGetTimeSplitsResponses = {
    /**
     * Response for status 200
     */
    200: Array<TimekeeperTimeSplitWid>;
};

export type TimekeeperGetTimeSplitsResponse = TimekeeperGetTimeSplitsResponses[keyof TimekeeperGetTimeSplitsResponses];

export type TimekeeperAddTimeSplitData = {
    body: TimekeeperTimeSplit;
    path?: never;
    query?: never;
    url: '/timekeeper/time-split';
};

export type TimekeeperAddTimeSplitErrors = {
    /**
     * Response for status 401
     */
    401: string;
};

export type TimekeeperAddTimeSplitError = TimekeeperAddTimeSplitErrors[keyof TimekeeperAddTimeSplitErrors];

export type TimekeeperAddTimeSplitResponses = {
    /**
     * Response for status 200
     */
    200: {
        time_split_id: string | number;
    };
};

export type TimekeeperAddTimeSplitResponse = TimekeeperAddTimeSplitResponses[keyof TimekeeperAddTimeSplitResponses];

export type TimekeeperDeleteTimeSplitData = {
    body?: never;
    path: {
        id: string | number;
    };
    query?: never;
    url: '/timekeeper/time-split/{id}';
};

export type TimekeeperDeleteTimeSplitErrors = {
    /**
     * Response for status 401
     */
    401: string;
    /**
     * Response for status 404
     */
    404: string;
};

export type TimekeeperDeleteTimeSplitError = TimekeeperDeleteTimeSplitErrors[keyof TimekeeperDeleteTimeSplitErrors];

export type TimekeeperDeleteTimeSplitResponses = {
    /**
     * Response for status 200
     */
    200: string;
};

export type TimekeeperDeleteTimeSplitResponse = TimekeeperDeleteTimeSplitResponses[keyof TimekeeperDeleteTimeSplitResponses];

export type TimekeeperModifyTimeSplitData = {
    body: TimekeeperTimeSplit;
    path: {
        id: string | number;
    };
    query?: never;
    url: '/timekeeper/time-split/{id}';
};

export type TimekeeperModifyTimeSplitErrors = {
    /**
     * Response for status 401
     */
    401: string;
    /**
     * Response for status 404
     */
    404: string;
};

export type TimekeeperModifyTimeSplitError = TimekeeperModifyTimeSplitErrors[keyof TimekeeperModifyTimeSplitErrors];

export type TimekeeperModifyTimeSplitResponses = {
    /**
     * Response for status 200
     */
    200: string;
};

export type TimekeeperModifyTimeSplitResponse = TimekeeperModifyTimeSplitResponses[keyof TimekeeperModifyTimeSplitResponses];

export type AuthDeleteLoginData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type AuthDeleteLoginErrors = {
    /**
     * It's your fault
     */
    '4XX': string;
    /**
     * We're having a skill issue
     */
    '5XX': string;
};

export type AuthDeleteLoginError = AuthDeleteLoginErrors[keyof AuthDeleteLoginErrors];

export type AuthDeleteLoginResponses = {
    /**
     * Ok
     */
    200: unknown;
};

export type AuthLoginData = {
    body: AuthLogin;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type AuthLoginErrors = {
    /**
     * It's your fault
     */
    '4XX': string;
    /**
     * We're having a skill issue
     */
    '5XX': string;
};

export type AuthLoginError = AuthLoginErrors[keyof AuthLoginErrors];

export type AuthLoginResponses = {
    /**
     * Ok
     */
    200: AuthLoginToken;
};

export type AuthLoginResponse = AuthLoginResponses[keyof AuthLoginResponses];

export type AuthRefreshData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type AuthRefreshErrors = {
    /**
     * It's your fault
     */
    '4XX': string;
    /**
     * We're having a skill issue
     */
    '5XX': string;
};

export type AuthRefreshError = AuthRefreshErrors[keyof AuthRefreshErrors];

export type AuthRefreshResponses = {
    /**
     * Ok
     */
    200: AuthLoginToken;
};

export type AuthRefreshResponse = AuthRefreshResponses[keyof AuthRefreshResponses];

export type AuthSignupData = {
    body: AuthInsertableDatabaseUser;
    path?: never;
    query?: never;
    url: '/auth/signup';
};

export type AuthSignupErrors = {
    /**
     * It's your fault
     */
    '4XX': string;
    /**
     * We're having a skill issue
     */
    '5XX': string;
};

export type AuthSignupError = AuthSignupErrors[keyof AuthSignupErrors];

export type AuthSignupResponses = {
    /**
     * Ok
     */
    200: AuthLoginToken;
};

export type AuthSignupResponse = AuthSignupResponses[keyof AuthSignupResponses];
