// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type TimekeeperTimer = {
    time_split: string | number;
    start_timestamp: string | number;
    end_timestamp: string | number;
    work: boolean;
    tags: Array<string | number>;
};

export type TimekeeperTimerWid = {
    id: string | number;
    time_split: string | number;
    start_timestamp: string | number;
    end_timestamp: string | number;
    work: boolean;
    tags: Array<string | number>;
};

export type TimekeeperTag = {
    name: string;
};

export type TimekeeperTagWid = {
    id: string | number;
    name: string;
};

export type TimekeeperTimeSplitTimer = {
    len: string | number;
    name: string;
    work: boolean;
};

export type TimekeeperTimeSplit = {
    name: string;
    description: string;
    deleted: boolean;
    timers: Array<{
        len: string | number;
        name: string;
        work: boolean;
    }>;
};

export type TimekeeperTimeSplitWid = {
    id: string | number;
    name: string;
    description: string;
    deleted: boolean;
    timers: Array<{
        len: string | number;
        name: string;
        work: boolean;
    }>;
};

export type AuthDatabaseUserPassword = {
    password: string;
};

export type AuthInsertableDatabaseUser = AuthDatabaseUserPassword & {
    username: string;
};

export type AuthLogin = {
    password: string;
    username: string;
};

export type AuthLoginTokens = {
    access_token: string;
    refresh_token: string;
};

export type AuthRefreshTokenQuery = {
    refresh_token: string;
};

export type TimekeeperGetIndexData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type TimekeeperGetIndexResponses = {
    /**
     * Response for status 200
     */
    200: {
        up: boolean;
    };
};

export type TimekeeperGetIndexResponse = TimekeeperGetIndexResponses[keyof TimekeeperGetIndexResponses];

export type TimekeeperGetTimekeeperTimerData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/timekeeper/timer';
};

export type TimekeeperGetTimekeeperTimerErrors = {
    /**
     * Response for status 401
     */
    401: string;
    /**
     * Response for status 404
     */
    404: string;
};

export type TimekeeperGetTimekeeperTimerError = TimekeeperGetTimekeeperTimerErrors[keyof TimekeeperGetTimekeeperTimerErrors];

export type TimekeeperGetTimekeeperTimerResponses = {
    /**
     * Response for status 200
     */
    200: Array<TimekeeperTimerWid>;
};

export type TimekeeperGetTimekeeperTimerResponse = TimekeeperGetTimekeeperTimerResponses[keyof TimekeeperGetTimekeeperTimerResponses];

export type TimekeeperPostTimekeeperTimerData = {
    body: TimekeeperTimer;
    path?: never;
    query?: never;
    url: '/timekeeper/timer';
};

export type TimekeeperPostTimekeeperTimerErrors = {
    /**
     * Response for status 401
     */
    401: string;
};

export type TimekeeperPostTimekeeperTimerError = TimekeeperPostTimekeeperTimerErrors[keyof TimekeeperPostTimekeeperTimerErrors];

export type TimekeeperPostTimekeeperTimerResponses = {
    /**
     * Response for status 200
     */
    200: {
        timer_id: string | number;
    };
};

export type TimekeeperPostTimekeeperTimerResponse = TimekeeperPostTimekeeperTimerResponses[keyof TimekeeperPostTimekeeperTimerResponses];

export type TimekeeperPutTimekeeperTimerByIdData = {
    body: TimekeeperTimer;
    path: {
        id: string | number;
    };
    query?: never;
    url: '/timekeeper/timer/{id}';
};

export type TimekeeperPutTimekeeperTimerByIdErrors = {
    /**
     * Response for status 401
     */
    401: string;
    /**
     * Response for status 404
     */
    404: string;
};

export type TimekeeperPutTimekeeperTimerByIdError = TimekeeperPutTimekeeperTimerByIdErrors[keyof TimekeeperPutTimekeeperTimerByIdErrors];

export type TimekeeperPutTimekeeperTimerByIdResponses = {
    /**
     * Response for status 200
     */
    200: string;
};

export type TimekeeperPutTimekeeperTimerByIdResponse = TimekeeperPutTimekeeperTimerByIdResponses[keyof TimekeeperPutTimekeeperTimerByIdResponses];

export type TimekeeperGetTimekeeperTagData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/timekeeper/tag';
};

export type TimekeeperGetTimekeeperTagErrors = {
    /**
     * Response for status 401
     */
    401: string;
};

export type TimekeeperGetTimekeeperTagError = TimekeeperGetTimekeeperTagErrors[keyof TimekeeperGetTimekeeperTagErrors];

export type TimekeeperGetTimekeeperTagResponses = {
    /**
     * Response for status 200
     */
    200: Array<TimekeeperTagWid>;
};

export type TimekeeperGetTimekeeperTagResponse = TimekeeperGetTimekeeperTagResponses[keyof TimekeeperGetTimekeeperTagResponses];

export type TimekeeperPostTimekeeperTagData = {
    body: TimekeeperTag;
    path?: never;
    query?: never;
    url: '/timekeeper/tag';
};

export type TimekeeperPostTimekeeperTagErrors = {
    /**
     * Response for status 401
     */
    401: string;
};

export type TimekeeperPostTimekeeperTagError = TimekeeperPostTimekeeperTagErrors[keyof TimekeeperPostTimekeeperTagErrors];

export type TimekeeperPostTimekeeperTagResponses = {
    /**
     * Response for status 200
     */
    200: {
        tag_id: string | number;
    };
};

export type TimekeeperPostTimekeeperTagResponse = TimekeeperPostTimekeeperTagResponses[keyof TimekeeperPostTimekeeperTagResponses];

export type TimekeeperDeleteTimekeeperTagByIdData = {
    body?: never;
    path: {
        id: string | number;
    };
    query?: never;
    url: '/timekeeper/tag/{id}';
};

export type TimekeeperDeleteTimekeeperTagByIdErrors = {
    /**
     * Response for status 401
     */
    401: string;
    /**
     * Response for status 404
     */
    404: string;
};

export type TimekeeperDeleteTimekeeperTagByIdError = TimekeeperDeleteTimekeeperTagByIdErrors[keyof TimekeeperDeleteTimekeeperTagByIdErrors];

export type TimekeeperDeleteTimekeeperTagByIdResponses = {
    /**
     * Response for status 200
     */
    200: string;
};

export type TimekeeperDeleteTimekeeperTagByIdResponse = TimekeeperDeleteTimekeeperTagByIdResponses[keyof TimekeeperDeleteTimekeeperTagByIdResponses];

export type TimekeeperPutTimekeeperTagByIdData = {
    body: TimekeeperTag;
    path: {
        id: string | number;
    };
    query?: never;
    url: '/timekeeper/tag/{id}';
};

export type TimekeeperPutTimekeeperTagByIdErrors = {
    /**
     * Response for status 401
     */
    401: string;
    /**
     * Response for status 404
     */
    404: string;
};

export type TimekeeperPutTimekeeperTagByIdError = TimekeeperPutTimekeeperTagByIdErrors[keyof TimekeeperPutTimekeeperTagByIdErrors];

export type TimekeeperPutTimekeeperTagByIdResponses = {
    /**
     * Response for status 200
     */
    200: string;
};

export type TimekeeperPutTimekeeperTagByIdResponse = TimekeeperPutTimekeeperTagByIdResponses[keyof TimekeeperPutTimekeeperTagByIdResponses];

export type TimekeeperGetTimekeeperTimeSplitData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/timekeeper/time-split';
};

export type TimekeeperGetTimekeeperTimeSplitErrors = {
    /**
     * Response for status 401
     */
    401: string;
};

export type TimekeeperGetTimekeeperTimeSplitError = TimekeeperGetTimekeeperTimeSplitErrors[keyof TimekeeperGetTimekeeperTimeSplitErrors];

export type TimekeeperGetTimekeeperTimeSplitResponses = {
    /**
     * Response for status 200
     */
    200: Array<TimekeeperTimeSplitWid>;
};

export type TimekeeperGetTimekeeperTimeSplitResponse = TimekeeperGetTimekeeperTimeSplitResponses[keyof TimekeeperGetTimekeeperTimeSplitResponses];

export type TimekeeperPostTimekeeperTimeSplitData = {
    body: TimekeeperTimeSplit;
    path?: never;
    query?: never;
    url: '/timekeeper/time-split';
};

export type TimekeeperPostTimekeeperTimeSplitErrors = {
    /**
     * Response for status 401
     */
    401: string;
};

export type TimekeeperPostTimekeeperTimeSplitError = TimekeeperPostTimekeeperTimeSplitErrors[keyof TimekeeperPostTimekeeperTimeSplitErrors];

export type TimekeeperPostTimekeeperTimeSplitResponses = {
    /**
     * Response for status 200
     */
    200: {
        time_split_id: string | number;
    };
};

export type TimekeeperPostTimekeeperTimeSplitResponse = TimekeeperPostTimekeeperTimeSplitResponses[keyof TimekeeperPostTimekeeperTimeSplitResponses];

export type TimekeeperDeleteTimekeeperTimeSplitByIdData = {
    body?: never;
    path: {
        id: string | number;
    };
    query?: never;
    url: '/timekeeper/time-split/{id}';
};

export type TimekeeperDeleteTimekeeperTimeSplitByIdErrors = {
    /**
     * Response for status 401
     */
    401: string;
    /**
     * Response for status 404
     */
    404: string;
};

export type TimekeeperDeleteTimekeeperTimeSplitByIdError = TimekeeperDeleteTimekeeperTimeSplitByIdErrors[keyof TimekeeperDeleteTimekeeperTimeSplitByIdErrors];

export type TimekeeperDeleteTimekeeperTimeSplitByIdResponses = {
    /**
     * Response for status 200
     */
    200: string;
};

export type TimekeeperDeleteTimekeeperTimeSplitByIdResponse = TimekeeperDeleteTimekeeperTimeSplitByIdResponses[keyof TimekeeperDeleteTimekeeperTimeSplitByIdResponses];

export type TimekeeperPutTimekeeperTimeSplitByIdData = {
    body: TimekeeperTimeSplit;
    path: {
        id: string | number;
    };
    query?: never;
    url: '/timekeeper/time-split/{id}';
};

export type TimekeeperPutTimekeeperTimeSplitByIdErrors = {
    /**
     * Response for status 401
     */
    401: string;
    /**
     * Response for status 404
     */
    404: string;
};

export type TimekeeperPutTimekeeperTimeSplitByIdError = TimekeeperPutTimekeeperTimeSplitByIdErrors[keyof TimekeeperPutTimekeeperTimeSplitByIdErrors];

export type TimekeeperPutTimekeeperTimeSplitByIdResponses = {
    /**
     * Response for status 200
     */
    200: string;
};

export type TimekeeperPutTimekeeperTimeSplitByIdResponse = TimekeeperPutTimekeeperTimeSplitByIdResponses[keyof TimekeeperPutTimekeeperTimeSplitByIdResponses];

export type AuthDeleteLoginData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type AuthDeleteLoginErrors = {
    /**
     * It's your fault
     */
    '4XX': string;
    /**
     * We're having a skill issue
     */
    '5XX': string;
};

export type AuthDeleteLoginError = AuthDeleteLoginErrors[keyof AuthDeleteLoginErrors];

export type AuthDeleteLoginResponses = {
    /**
     * Ok
     */
    200: unknown;
};

export type AuthLoginData = {
    body: AuthLogin;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type AuthLoginErrors = {
    /**
     * It's your fault
     */
    '4XX': string;
    /**
     * We're having a skill issue
     */
    '5XX': string;
};

export type AuthLoginError = AuthLoginErrors[keyof AuthLoginErrors];

export type AuthLoginResponses = {
    /**
     * Ok
     */
    200: AuthLoginTokens;
};

export type AuthLoginResponse = AuthLoginResponses[keyof AuthLoginResponses];

export type AuthRefreshData = {
    body: AuthRefreshTokenQuery;
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type AuthRefreshErrors = {
    /**
     * It's your fault
     */
    '4XX': string;
    /**
     * We're having a skill issue
     */
    '5XX': string;
};

export type AuthRefreshError = AuthRefreshErrors[keyof AuthRefreshErrors];

export type AuthRefreshResponses = {
    /**
     * Ok
     */
    200: AuthLoginTokens;
};

export type AuthRefreshResponse = AuthRefreshResponses[keyof AuthRefreshResponses];

export type AuthSignupData = {
    body: AuthInsertableDatabaseUser;
    path?: never;
    query?: never;
    url: '/auth/signup';
};

export type AuthSignupErrors = {
    /**
     * It's your fault
     */
    '4XX': string;
    /**
     * We're having a skill issue
     */
    '5XX': string;
};

export type AuthSignupError = AuthSignupErrors[keyof AuthSignupErrors];

export type AuthSignupResponses = {
    /**
     * Ok
     */
    200: AuthLoginTokens;
};

export type AuthSignupResponse = AuthSignupResponses[keyof AuthSignupResponses];
